# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple, Union
    VERSION_TUPLE = Tuple[Union[int, str], ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

# This dummy version is overridden by setuptools_scm during packaging.
__version__ = version = '0.0.3.dev3+ga9dc210.d20241101'
__version_tuple__ = version_tuple = (0, 0, 3, 'dev3', 'ga9dc210.d20241101')
